[project]
authors = ["pakiessling <pakiessling@ukaachen.de>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "colon_analysis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=6.29.5,<7"
bioconductor-edger = ">=4.4.0,<5"
r-irkernel = ">=1.3.2,<2"
r-pak = ">=0.8.0.1,<0.9"
scanpy = ">=1.10.4,<2"
bioconductor-singlecellexperiment = ">=1.28.0,<2"
gh = ">=2.66.0,<3"
r = ">=4.4,<4.5"
r-hdf5r = ">=1.3.12,<2"
bioconductor-genomeinfodb = ">=1.42.0,<2"
bioconductor-genomeinfodbdata = ">=1.2.13,<2"
bioconductor-msigdb = ">=1.14.0,<2"
bioconductor-gseabase = ">=1.68.0,<2"
r-argparser = ">=0.7.2,<0.8"
r-rcpp = ">=1.0.14,<2"
decoupler-py = ">=1.8.0,<2"
omnipath = ">=1.0.8,<2"
quarto = ">=1.6.40,<2"
