[project]
authors = ["pakiessling <pakiessling@ukaachen.de>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "colon_analysis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=6.29.5,<7"
bioconductor-edger = ">=4.4.0,<5"
bioconductor-scater = ">=1.34.0,<2"
r-irkernel = ">=1.3.2,<2"
r-pak = ">=0.8.0.1,<0.9"
scanpy = ">=1.10.4,<2"
bioconductor-singlecellexperiment = ">=1.28.0,<2"
